apiVersion: v1
kind: Service
metadata:
  labels:
    name: telemetry-server
  name: telemetry-server
  namespace: telemetry
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tele-server
      port: 8115
      protocol: TCP
      targetPort: 8115
  selector:
    name: telemetry-server
  type: LoadBalancer
