apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: telemetry
resources:
- ./deployment.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: telemetry-client
  literals:
  - CATTLE_URL=https://rancher.cattle-system/v3
  - TELEMETRY_TO_URL="http://telemetry-server:8115/publish"
  # - CATTLE_CERTIFICATE=""
