apiVersion: batch/v1
kind: Job
metadata:
  name: test-telemetry-server
  namespace: telemetry
spec:
  # ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: test-container
          image: alpine:3
          command:
            - sh
            - -c
            - |
              set -ex && apk update && apk add curl jq httpie

              test $(curl -fsSL \
                -u "$access_key:$secret_key" \
                http://telemetry-server:8115/admin/active?hours=48 | \
                   jq '.data[0].record.cluster.active') -eq 1 ||
                     >&2 echo "error: no active cluster"
          envFrom:
            - secretRef:
                name: telemetry
      restartPolicy: OnFailure
