apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: telemetry

resources:
  - deployment.yaml
  - service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: pgadmin
    literals:
      - pgadminpassword=admin
    files:
      - ./servers.json

  - name: postgresql
    files:
      - ./create_db.sql
