apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: telemetry

resources:
  - deployment.yaml
  - service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: telemetry-server
    literals:
      - "TELEMETRY_PG_USER=admin"
      - "TELEMETRY_PG_PASS=admin"
      - "TELEMETRY_PG_HOST=postgresql"
