apiVersion: 1

deleteDatasources:
    - name: telemetry

datasources:
  - name: telemetry
    type: influxdb
    access: proxy
    database: telemetry
    # user: grafana
    url: http://influxdb:8086
    jsonData:
      httpMode: GET
    # secureJsonData:
    #   password: grafana
