apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-stats
spec:
  template:
    spec:
      containers:
      - name: telemetry-stats
        image: rancherlabs/rancher-telemetry-stats:dev
        imagePullPolicy: Never
