
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: telemetry

generatorOptions:
  disableNameSuffixHash: true

resources:
- ../base

images:
- name: rancherlabs/rancher-telemetry-stats
  newTag: dev
