
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: telemetry

resources:
- ../base

patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      name: telemetry-stats
