apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin
  namespace: telemetry
data:

  servers.json: > # pgadmin configuration
    {
        "Servers": {
            "1": {
                "Name": "postgresql",
                "Group": "Servers",
                "Port": 5432,
                "Username": "admin",
                "Host": "localhost",
                "SSLMode": "prefer",
                "MaintenanceDB": "telemetry",
                "PassFile": "/pgadminpassword"
            }
        }
    }
  pgadminpassword: admin

