apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: postgresql
  name: postgresql
data:
  servers.json: >
    {
        "Servers": {
            "1": {
                "Name": "postgresql",
                "Group": "Servers",
                "Port": 5432,
                "Username": "admin",
                "Host": "localhost",
                "SSLMode": "prefer",
                "MaintenanceDB": "telemetry",
                "PassFile": "/pgadminpassword"
            }
        }
    }
  pgadminpassword: admin

