apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: telemetry

resources:
  - ./../base

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: rancher/telemetry
    newTag: dev

configMapGenerator:
  - name: telemetry-server
    behavior: merge
    literals:
      - DEBUG=true
