apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: telemetry

resources:
  - ../base

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      name: telemetry-server

configMapGenerator:
  - name: telemetry-server
    behavior: merge
    literals:
      - DEBUG=true
