apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: telemetry

resources:
  - ../base

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      name: telemetry-client

configMapGenerator:
  - name: telemetry-client
    behavior: merge
    literals:
      - DEBUG=true
      - TELEMETRY_INTERVAL=1m
