name: E2E
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'
      - 'master'
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install K3d
        run: curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

      - name: Install httpie
        run: pip install httpie

      - name: Run it
        run: SKIP_ETC_HOSTS=yes ./start

      - name: Test report retrieval from PostgreSQL through Telemetry Server
        run: |
          set -x
          ns="${ns:-telemetry}"
          kubectl -n "${ns}" apply --wait -k manifests/tests
          kubectl -n telemetry wait \
            --for=condition=complete \
            --timeout=900s \
            job/test-telemetry-server

      - name: Collect logs
        if: failure()
        run: |
          bash kubectl-dump telemetry

      - name: Upload logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: gha-telemetry-dev-e2e-logs-${{ github.sha }}-${{ matrix.k3s_version }}-${{ github.run_id }}
          path: |
            k8s-debug-*
          retention-days: 2
