name: Smoke test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'
      - 'master'
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install K3d
        run: curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

      - name: Install httpie
        run: pip install httpie

      - name: Run it
        run: ./start
