name: E2E
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'
      - 'master'
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install K3d
        run: curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

      - name: Install httpie
        run: pip install httpie

      - name: Run it
        run: SKIP_ETC_HOSTS=yes ./start

      - name: Test report retrieval from PostgreSQL through Telemetry Server
        run: |
          kubectl -n telemetry apply --wait -k manifests/tests
          kubectl -n telemetry wait --for=condition=complete --timeout=30s job/test-telemetry-server

