name: E2E
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'
      - 'master'
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install K3d
        run: curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

      - name: Install httpie
        run: pip install httpie

      - name: Run it
        run: SKIP_ETC_HOSTS=yes ./start

      - name: Test report retrieval from PostgreSQL through Telemetry Server
        run: |
          set -x

          ns="${ns:-telemetry}"

          kubectl -n "${ns}" apply --wait -k manifests/tests
          if ! kubectl -n telemetry wait \
            --for=condition=complete \
            --timeout=900s \
            job/test-telemetry-server; then

            for deployment in $(kubectl -n ${ns} get deployments -o name); do
              echo "==> ${deployment} <=="
              kubectl -n "${ns}" describe $deployment
              kubectl -n "${ns}" logs $deployment
            done

            for service in $(kubectl -n ${ns} get services -o name); do
              kubectl -n "${ns}" describe $service
            done

            for pod in $(kubectl -n ${ns} get pods -o name); do
              echo "==> ${pod} <=="
              kubectl -n "${ns}" describe $pod
              kubectl -n "${ns}" logs $pod
            done

            exit 1
          fi

