name: Kustomize test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'
      - 'master'
jobs:
  kustomize-builds-test:
    runs-on: ubuntu-latest
    steps:
      - name: test kustomize builds
        run: |
          apt update && apt install fish -y && fish test
